### ISSUE TITLE
Update Standalone Delegation example > JS Version (2.3.9)

### ISSUE THREAD

**Issue by ValentinJapan** [airgap-it/beacon-docs#28]
On the page 
https://docs.walletbeacon.io/guides/standalone-delegation/

Version displayed( 2.2.3)
https://unpkg.com/@airgap/beacon-sdk@2.2.3/dist/walletbeacon.min.js

Last version (2.3.9)
https://unpkg.com/@airgap/beacon-sdk@2.3.9/dist/walletbeacon.min.js

So please update the link and the SHA integrity

<script src="https://unpkg.com/@airgap/beacon-sdk@2.3.9/dist/walletbeacon.min.js" integrity="sha384-qmlJoOjIzO/W50x5NQfLoWd8+KZz849XPXME8fGj3XvPdj2ME5ZnTWUQ0Lhd2Mmb" crossorigin="anonymous"></script>

**Comment by AndreasGassmann** [comment]
I updated the link: https://github.com/airgap-it/beacon-docs/commit/5ebe3a47efb56cc7461ee188e5ea405c6895d2ba
